// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iaohmrohaopyuqtsovay.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlhb2htcm9oYW9weXVxdHNvdmF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2ODYwNjMsImV4cCI6MjA2MTI2MjA2M30.ZYBoxPda5vxkmZnhs_jnWEvaodHElewT0mFbrXW2yN0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);